//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripasDeGatoCliente.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TripasDeGatoCliente.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add.
        /// </summary>
        public static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Friend.
        /// </summary>
        public static string btnAddFriend {
            get {
                return ResourceManager.GetString("btnAddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        public static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends.
        /// </summary>
        public static string btnFriends {
            get {
                return ResourceManager.GetString("btnFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guest.
        /// </summary>
        public static string btnGuest {
            get {
                return ResourceManager.GetString("btnGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invite Friend.
        /// </summary>
        public static string btnInviteFriend {
            get {
                return ResourceManager.GetString("btnInviteFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join game.
        /// </summary>
        public static string btnJoinGame {
            get {
                return ResourceManager.GetString("btnJoinGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leaderboard.
        /// </summary>
        public static string btnLeaderboard {
            get {
                return ResourceManager.GetString("btnLeaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leave.
        /// </summary>
        public static string btnLeaveRoom {
            get {
                return ResourceManager.GetString("btnLeaveRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile.
        /// </summary>
        public static string btnProfile {
            get {
                return ResourceManager.GetString("btnProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove.
        /// </summary>
        public static string btnRemoveFriend {
            get {
                return ResourceManager.GetString("btnRemoveFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resend Code.
        /// </summary>
        public static string btnResendCode {
            get {
                return ResourceManager.GetString("btnResendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign In.
        /// </summary>
        public static string btnSignIn {
            get {
                return ResourceManager.GetString("btnSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign Out.
        /// </summary>
        public static string btnSignOut {
            get {
                return ResourceManager.GetString("btnSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start game.
        /// </summary>
        public static string btnStartGame {
            get {
                return ResourceManager.GetString("btnStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validate.
        /// </summary>
        public static string btnValidate {
            get {
                return ResourceManager.GetString("btnValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player.
        /// </summary>
        public static string columnPlayer {
            get {
                return ResourceManager.GetString("columnPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Points.
        /// </summary>
        public static string columnPoints {
            get {
                return ResourceManager.GetString("columnPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error creating account. Please try again.
        /// </summary>
        public static string dialogAccountCreatedErrror {
            get {
                return ResourceManager.GetString("dialogAccountCreatedErrror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account created successfully!.
        /// </summary>
        public static string dialogAccountCreatedSuccesfully {
            get {
                return ResourceManager.GetString("dialogAccountCreatedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connection error with the server.
        /// </summary>
        public static string dialogConnectionErrorWithServer {
            get {
                return ResourceManager.GetString("dialogConnectionErrorWithServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This email is already registered. Please use a different email.
        /// </summary>
        public static string dialogEmailInUse {
            get {
                return ResourceManager.GetString("dialogEmailInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid Email.
        /// </summary>
        public static string dialogInvalidEmail {
            get {
                return ResourceManager.GetString("dialogInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid Password.
        /// </summary>
        public static string dialogInvalidPassword {
            get {
                return ResourceManager.GetString("dialogInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Credentials do not match.
        /// </summary>
        public static string dialogMissmatchesCredentials {
            get {
                return ResourceManager.GetString("dialogMissmatchesCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user profile could not be retrieved.
        /// </summary>
        public static string dialogNotRetrievedProfile {
            get {
                return ResourceManager.GetString("dialogNotRetrievedProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmation.
        /// </summary>
        public static string dialogTitleConfirmation {
            get {
                return ResourceManager.GetString("dialogTitleConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string dialogTitleError {
            get {
                return ResourceManager.GetString("dialogTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Succes.
        /// </summary>
        public static string dialogTitleSucces {
            get {
                return ResourceManager.GetString("dialogTitleSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning.
        /// </summary>
        public static string dialogTitleWarning {
            get {
                return ResourceManager.GetString("dialogTitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wrong Data.
        /// </summary>
        public static string dialogWrongData {
            get {
                return ResourceManager.GetString("dialogWrongData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string globalBtnBack {
            get {
                return ResourceManager.GetString("globalBtnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ok.
        /// </summary>
        public static string globalBtnOk {
            get {
                return ResourceManager.GetString("globalBtnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kick player.
        /// </summary>
        public static string globalKick {
            get {
                return ResourceManager.GetString("globalKick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        public static string globalLbUser {
            get {
                return ResourceManager.GetString("globalLbUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm password.
        /// </summary>
        public static string lbConfirmPasswordSignIn {
            get {
                return ResourceManager.GetString("lbConfirmPasswordSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you wish to remove {0} from your friends list?.
        /// </summary>
        public static string lbDeleteFriend {
            get {
                return ResourceManager.GetString("lbDeleteFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Duration:.
        /// </summary>
        public static string lbDuration {
            get {
                return ResourceManager.GetString("lbDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string lbEmail {
            get {
                return ResourceManager.GetString("lbEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valid example: user@domain.com.
        /// </summary>
        public static string lbEmailValid {
            get {
                return ResourceManager.GetString("lbEmailValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please choose a compatible file type.
        /// </summary>
        public static string lbFileFormat {
            get {
                return ResourceManager.GetString("lbFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game Name:.
        /// </summary>
        public static string lbGameName {
            get {
                return ResourceManager.GetString("lbGameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove player?.
        /// </summary>
        public static string lbKick {
            get {
                return ResourceManager.GetString("lbKick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string lbLanguage {
            get {
                return ResourceManager.GetString("lbLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Map:.
        /// </summary>
        public static string lbMap {
            get {
                return ResourceManager.GetString("lbMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Message.
        /// </summary>
        public static string lbMessage {
            get {
                return ResourceManager.GetString("lbMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nodes:.
        /// </summary>
        public static string lbNodes {
            get {
                return ResourceManager.GetString("lbNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tehere&apos;s no one else in the room.
        /// </summary>
        public static string lbNoOneKick {
            get {
                return ResourceManager.GetString("lbNoOneKick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string lbPassword {
            get {
                return ResourceManager.GetString("lbPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string lbPasswordSignIn {
            get {
                return ResourceManager.GetString("lbPasswordSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 10 to 50 characters, with letters and numbers.
        /// </summary>
        public static string lbPasswordValid {
            get {
                return ResourceManager.GetString("lbPasswordValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recover Password.
        /// </summary>
        public static string lbRecoverPassword {
            get {
                return ResourceManager.GetString("lbRecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 5 to 50 characters. Use letters, numbers, or _.
        /// </summary>
        public static string lbUserNameValid {
            get {
                return ResourceManager.GetString("lbUserNameValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Action failed.
        /// </summary>
        public static string titleActionFailed {
            get {
                return ResourceManager.GetString("titleActionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete friend.
        /// </summary>
        public static string titleDeleteFriend {
            get {
                return ResourceManager.GetString("titleDeleteFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Format not supported.
        /// </summary>
        public static string titleFileFormat {
            get {
                return ResourceManager.GetString("titleFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leave room.
        /// </summary>
        public static string titleLeaveRoom {
            get {
                return ResourceManager.GetString("titleLeaveRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No one to kick.
        /// </summary>
        public static string titleNoOneKick {
            get {
                return ResourceManager.GetString("titleNoOneKick", resourceCulture);
            }
        }
    }
}
