//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripasDeGatoCliente.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TripasDeGatoCliente.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add.
        /// </summary>
        public static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Friend.
        /// </summary>
        public static string btnAddFriend {
            get {
                return ResourceManager.GetString("btnAddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continue.
        /// </summary>
        public static string btnContinue {
            get {
                return ResourceManager.GetString("btnContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create.
        /// </summary>
        public static string btnCreate {
            get {
                return ResourceManager.GetString("btnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        public static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends.
        /// </summary>
        public static string btnFriends {
            get {
                return ResourceManager.GetString("btnFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guest.
        /// </summary>
        public static string btnGuest {
            get {
                return ResourceManager.GetString("btnGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invite.
        /// </summary>
        public static string btnInvited {
            get {
                return ResourceManager.GetString("btnInvited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invite Friend.
        /// </summary>
        public static string btnInviteFriend {
            get {
                return ResourceManager.GetString("btnInviteFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join game.
        /// </summary>
        public static string btnJoinGame {
            get {
                return ResourceManager.GetString("btnJoinGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leaderboard.
        /// </summary>
        public static string btnLeaderboard {
            get {
                return ResourceManager.GetString("btnLeaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leave.
        /// </summary>
        public static string btnLeaveRoom {
            get {
                return ResourceManager.GetString("btnLeaveRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile.
        /// </summary>
        public static string btnProfile {
            get {
                return ResourceManager.GetString("btnProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove.
        /// </summary>
        public static string btnRemoveFriend {
            get {
                return ResourceManager.GetString("btnRemoveFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resend Code.
        /// </summary>
        public static string btnResendCode {
            get {
                return ResourceManager.GetString("btnResendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save password.
        /// </summary>
        public static string btnSavePassword {
            get {
                return ResourceManager.GetString("btnSavePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        public static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send.
        /// </summary>
        public static string btnSend {
            get {
                return ResourceManager.GetString("btnSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign In.
        /// </summary>
        public static string btnSignIn {
            get {
                return ResourceManager.GetString("btnSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign Out.
        /// </summary>
        public static string btnSignOut {
            get {
                return ResourceManager.GetString("btnSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start game.
        /// </summary>
        public static string btnStartGame {
            get {
                return ResourceManager.GetString("btnStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validate.
        /// </summary>
        public static string btnValidate {
            get {
                return ResourceManager.GetString("btnValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player.
        /// </summary>
        public static string columnPlayer {
            get {
                return ResourceManager.GetString("columnPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Points.
        /// </summary>
        public static string columnPoints {
            get {
                return ResourceManager.GetString("columnPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error creating account. Please try again.
        /// </summary>
        public static string dialogAccountCreatedErrror {
            get {
                return ResourceManager.GetString("dialogAccountCreatedErrror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account created successfully!.
        /// </summary>
        public static string dialogAccountCreatedSuccesfully {
            get {
                return ResourceManager.GetString("dialogAccountCreatedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend &apos;{0}&apos; added successfully.
        /// </summary>
        public static string dialogAddFriendSuccessfully {
            get {
                return ResourceManager.GetString("dialogAddFriendSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You cannot add yourself as a friend.
        /// </summary>
        public static string dialogCannotAddSelfAsFriend {
            get {
                return ResourceManager.GetString("dialogCannotAddSelfAsFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los cambios se han guardado correctamente.
        /// </summary>
        public static string dialogChangesSaved {
            get {
                return ResourceManager.GetString("dialogChangesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chat communication error: {0}.
        /// </summary>
        public static string dialogChatCommunicationError {
            get {
                return ResourceManager.GetString("dialogChatCommunicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Communication error. Please try again later.
        /// </summary>
        public static string dialogCommunicationError {
            get {
                return ResourceManager.GetString("dialogCommunicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please complete the fields correctly.
        /// </summary>
        public static string dialogCompleteFieldsError {
            get {
                return ResourceManager.GetString("dialogCompleteFieldsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to establish a connection with the server. Please check your internet connection and try it again..
        /// </summary>
        public static string dialogComunicationException {
            get {
                return ResourceManager.GetString("dialogComunicationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to kick the player from the lobby?.
        /// </summary>
        public static string dialogConfirmKickPlayer {
            get {
                return ResourceManager.GetString("dialogConfirmKickPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not connect to the lobby..
        /// </summary>
        public static string dialogConnectionError {
            get {
                return ResourceManager.GetString("dialogConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connection error with the server.
        /// </summary>
        public static string dialogConnectionErrorWithServer {
            get {
                return ResourceManager.GetString("dialogConnectionErrorWithServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This email is already registered. Please use a different email.
        /// </summary>
        public static string dialogEmailInUse {
            get {
                return ResourceManager.GetString("dialogEmailInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to find the endpoint. Please check the server configuration and try again..
        /// </summary>
        public static string dialogEndPointException {
            get {
                return ResourceManager.GetString("dialogEndPointException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter a name for the game..
        /// </summary>
        public static string dialogEnterGameNameError {
            get {
                return ResourceManager.GetString("dialogEnterGameNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error adding friend. Please try again.
        /// </summary>
        public static string dialogErrorAddingFriend {
            get {
                return ResourceManager.GetString("dialogErrorAddingFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error checking the email.
        /// </summary>
        public static string dialogErrorCheckingEmail {
            get {
                return ResourceManager.GetString("dialogErrorCheckingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error checking the username.
        /// </summary>
        public static string dialogErrorCheckingUserName {
            get {
                return ResourceManager.GetString("dialogErrorCheckingUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error creating the lobby. Please try again.
        /// </summary>
        public static string dialogErrorCreatingLobby {
            get {
                return ResourceManager.GetString("dialogErrorCreatingLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error deleting friendship. Please try again.
        /// </summary>
        public static string dialogErrorDeletingFriendship {
            get {
                return ResourceManager.GetString("dialogErrorDeletingFriendship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while trying to delete the friendship: {0}.
        /// </summary>
        public static string dialogErrorDeletingFriendshipDetails {
            get {
                return ResourceManager.GetString("dialogErrorDeletingFriendshipDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while loading the friends list: {0}.
        /// </summary>
        public static string dialogErrorLoadingFriendsList {
            get {
                return ResourceManager.GetString("dialogErrorLoadingFriendsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error resending the recovery code.
        /// </summary>
        public static string dialogErrorResendingRecoveryCode {
            get {
                return ResourceManager.GetString("dialogErrorResendingRecoveryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error resending verification code. Please try again.
        /// </summary>
        public static string dialogErrorResendingVerificationCode {
            get {
                return ResourceManager.GetString("dialogErrorResendingVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error saving profile: {0}.
        /// </summary>
        public static string dialogErrorSavingProfile {
            get {
                return ResourceManager.GetString("dialogErrorSavingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was an error saving the profile data.
        /// </summary>
        public static string dialogErrorSavingProfileData {
            get {
                return ResourceManager.GetString("dialogErrorSavingProfileData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while sending the invitation. Please try again later..
        /// </summary>
        public static string dialogErrorSendingInvitation {
            get {
                return ResourceManager.GetString("dialogErrorSendingInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error sending the recovery code.
        /// </summary>
        public static string dialogErrorSendingRecoveryCode {
            get {
                return ResourceManager.GetString("dialogErrorSendingRecoveryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error sending verification code. Please try again.
        /// </summary>
        public static string dialogErrorSendingVerificationCode {
            get {
                return ResourceManager.GetString("dialogErrorSendingVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error updating the password.
        /// </summary>
        public static string dialogErrorUpdatingPassowrd {
            get {
                return ResourceManager.GetString("dialogErrorUpdatingPassowrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error updating the player&apos;s status.
        /// </summary>
        public static string dialogErrorUpdatingPlayerStatus {
            get {
                return ResourceManager.GetString("dialogErrorUpdatingPlayerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friendship with &apos;{0}&apos; deleted successfully.
        /// </summary>
        public static string dialogFriendshipDeleted {
            get {
                return ResourceManager.GetString("dialogFriendshipDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The host left the lobby..
        /// </summary>
        public static string dialogHostLeftLobby {
            get {
                return ResourceManager.GetString("dialogHostLeftLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid Email.
        /// </summary>
        public static string dialogInvalidEmail {
            get {
                return ResourceManager.GetString("dialogInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The game name is invalid. Please choose a valid name..
        /// </summary>
        public static string dialogInvalidGameNameError {
            get {
                return ResourceManager.GetString("dialogInvalidGameNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: the guest profile or lobby code is invalid..
        /// </summary>
        public static string dialogInvalidGuestProfileOrLobbyCode {
            get {
                return ResourceManager.GetString("dialogInvalidGuestProfileOrLobbyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter a valid name.
        /// </summary>
        public static string dialogInvalidName {
            get {
                return ResourceManager.GetString("dialogInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid Password.
        /// </summary>
        public static string dialogInvalidPassword {
            get {
                return ResourceManager.GetString("dialogInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid recovery code. Please try again.
        /// </summary>
        public static string dialogInvalidRecoveryCode {
            get {
                return ResourceManager.GetString("dialogInvalidRecoveryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid time selected..
        /// </summary>
        public static string dialogInvalidTimeSelected {
            get {
                return ResourceManager.GetString("dialogInvalidTimeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid verification code. Please try again.
        /// </summary>
        public static string dialogInvalidVerificationCode {
            get {
                return ResourceManager.GetString("dialogInvalidVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The invitation has been successfully sent to {0}..
        /// </summary>
        public static string dialogInvitationSent {
            get {
                return ResourceManager.GetString("dialogInvitationSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have been kicked from the Lobby.
        /// </summary>
        public static string dialogKickedFromLobby {
            get {
                return ResourceManager.GetString("dialogKickedFromLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not create the lobby. Please try again..
        /// </summary>
        public static string dialogLobbyCreationError {
            get {
                return ResourceManager.GetString("dialogLobbyCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have been removed from the lobby..
        /// </summary>
        public static string dialogLobbyExit {
            get {
                return ResourceManager.GetString("dialogLobbyExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not join the lobby. It might be full or unavailable..
        /// </summary>
        public static string dialogLobbyJoinError {
            get {
                return ResourceManager.GetString("dialogLobbyJoinError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No lobbies found with that code..
        /// </summary>
        public static string dialogLobbyNotFound {
            get {
                return ResourceManager.GetString("dialogLobbyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to change the language? This will restart the game..
        /// </summary>
        public static string dialogMessageLanguagechange {
            get {
                return ResourceManager.GetString("dialogMessageLanguagechange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Credentials do not match.
        /// </summary>
        public static string dialogMissmatchesCredentials {
            get {
                return ResourceManager.GetString("dialogMissmatchesCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Navigation error. Please try again later.
        /// </summary>
        public static string dialogNavigationError {
            get {
                return ResourceManager.GetString("dialogNavigationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user profile could not be retrieved.
        /// </summary>
        public static string dialogNotRetrievedProfile {
            get {
                return ResourceManager.GetString("dialogNotRetrievedProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter an email address.
        /// </summary>
        public static string dialogNullEmail {
            get {
                return ResourceManager.GetString("dialogNullEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password has been successfully updated.
        /// </summary>
        public static string dialogPasswordUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("dialogPasswordUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The player is already online. It is not possible to log in again..
        /// </summary>
        public static string dialogPlayerAlreadyOnline {
            get {
                return ResourceManager.GetString("dialogPlayerAlreadyOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No profile matching that name was found.
        /// </summary>
        public static string dialogProfileNotFound {
            get {
                return ResourceManager.GetString("dialogProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A recovery code has been sent to your email.
        /// </summary>
        public static string dialogRecoveryCodeHasBeenSent {
            get {
                return ResourceManager.GetString("dialogRecoveryCodeHasBeenSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recovery code resent successfully.
        /// </summary>
        public static string dialogRecoveryCodeResent {
            get {
                return ResourceManager.GetString("dialogRecoveryCodeResent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The request has timed out. Please try again later.
        /// </summary>
        public static string dialogRequestTimeout {
            get {
                return ResourceManager.GetString("dialogRequestTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please select a friend to delete.
        /// </summary>
        public static string dialogSelectFriendToDelete {
            get {
                return ResourceManager.GetString("dialogSelectFriendToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please select a friend before sending the invitation..
        /// </summary>
        public static string dialogSelectFriendToInvite {
            get {
                return ResourceManager.GetString("dialogSelectFriendToInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please select a lobby to join..
        /// </summary>
        public static string dialogSelectLobbyToJoin {
            get {
                return ResourceManager.GetString("dialogSelectLobbyToJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please select the nodes, map, and time for the game..
        /// </summary>
        public static string dialogSelectNodesMapTimeError {
            get {
                return ResourceManager.GetString("dialogSelectNodesMapTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Try again waiting time has expired. Please check your connection to the server..
        /// </summary>
        public static string dialogTimeOutException {
            get {
                return ResourceManager.GetString("dialogTimeOutException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmation.
        /// </summary>
        public static string dialogTitleConfirmation {
            get {
                return ResourceManager.GetString("dialogTitleConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string dialogTitleError {
            get {
                return ResourceManager.GetString("dialogTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Succes.
        /// </summary>
        public static string dialogTitleSucces {
            get {
                return ResourceManager.GetString("dialogTitleSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning.
        /// </summary>
        public static string dialogTitleWarning {
            get {
                return ResourceManager.GetString("dialogTitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred: {0}.
        /// </summary>
        public static string dialogUnexpectedError {
            get {
                return ResourceManager.GetString("dialogUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} has joined the chat.
        /// </summary>
        public static string dialogUserJoinedChat {
            get {
                return ResourceManager.GetString("dialogUserJoinedChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The username is already in use.
        /// </summary>
        public static string dialogUserNameInUse {
            get {
                return ResourceManager.GetString("dialogUserNameInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verification code resent successfully. Please check your email.
        /// </summary>
        public static string dialogVerificationCodeResentSuccessfully {
            get {
                return ResourceManager.GetString("dialogVerificationCodeResentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verification code sent successfully. Please check your email.
        /// </summary>
        public static string dialogVerificationCodeSent {
            get {
                return ResourceManager.GetString("dialogVerificationCodeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Waiting for player....
        /// </summary>
        public static string dialogWaitingForPlayer {
            get {
                return ResourceManager.GetString("dialogWaitingForPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wrong Data.
        /// </summary>
        public static string dialogWrongData {
            get {
                return ResourceManager.GetString("dialogWrongData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string globalBtnBack {
            get {
                return ResourceManager.GetString("globalBtnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ok.
        /// </summary>
        public static string globalBtnOk {
            get {
                return ResourceManager.GetString("globalBtnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kick player.
        /// </summary>
        public static string globalKick {
            get {
                return ResourceManager.GetString("globalKick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code lobby.
        /// </summary>
        public static string globalLbEnterCodeLobby {
            get {
                return ResourceManager.GetString("globalLbEnterCodeLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player 1.
        /// </summary>
        public static string globalLbPlayer1 {
            get {
                return ResourceManager.GetString("globalLbPlayer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player 2.
        /// </summary>
        public static string globalLbPlayer2 {
            get {
                return ResourceManager.GetString("globalLbPlayer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        public static string globalLbUser {
            get {
                return ResourceManager.GetString("globalLbUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code.
        /// </summary>
        public static string headerCode {
            get {
                return ResourceManager.GetString("headerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name Game.
        /// </summary>
        public static string headerGameName {
            get {
                return ResourceManager.GetString("headerGameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nodes.
        /// </summary>
        public static string headerNodes {
            get {
                return ResourceManager.GetString("headerNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Players.
        /// </summary>
        public static string headerPlayers {
            get {
                return ResourceManager.GetString("headerPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code.
        /// </summary>
        public static string lbCode {
            get {
                return ResourceManager.GetString("lbCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm password.
        /// </summary>
        public static string lbConfirmPasswordSignIn {
            get {
                return ResourceManager.GetString("lbConfirmPasswordSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you wish to remove {0} from your friends list?.
        /// </summary>
        public static string lbDeleteFriend {
            get {
                return ResourceManager.GetString("lbDeleteFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Duration:.
        /// </summary>
        public static string lbDuration {
            get {
                return ResourceManager.GetString("lbDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string lbEmail {
            get {
                return ResourceManager.GetString("lbEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valid example: user@domain.com.
        /// </summary>
        public static string lbEmailValid {
            get {
                return ResourceManager.GetString("lbEmailValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your email.
        /// </summary>
        public static string lbEnterEmail {
            get {
                return ResourceManager.GetString("lbEnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your new password.
        /// </summary>
        public static string lbEnterNewPassword {
            get {
                return ResourceManager.GetString("lbEnterNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the recovery code:.
        /// </summary>
        public static string lbEnterRecoveryCode {
            get {
                return ResourceManager.GetString("lbEnterRecoveryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the verification code:.
        /// </summary>
        public static string lbEnterVerificationCode {
            get {
                return ResourceManager.GetString("lbEnterVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please choose a compatible file type.
        /// </summary>
        public static string lbFileFormat {
            get {
                return ResourceManager.GetString("lbFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game Name:.
        /// </summary>
        public static string lbGameName {
            get {
                return ResourceManager.GetString("lbGameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove player?.
        /// </summary>
        public static string lbKick {
            get {
                return ResourceManager.GetString("lbKick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string lbLanguage {
            get {
                return ResourceManager.GetString("lbLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language Change.
        /// </summary>
        public static string lbLanguageChange {
            get {
                return ResourceManager.GetString("lbLanguageChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Map:.
        /// </summary>
        public static string lbMap {
            get {
                return ResourceManager.GetString("lbMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Message.
        /// </summary>
        public static string lbMessage {
            get {
                return ResourceManager.GetString("lbMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nodes:.
        /// </summary>
        public static string lbNodes {
            get {
                return ResourceManager.GetString("lbNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tehere&apos;s no one else in the room.
        /// </summary>
        public static string lbNoOneKick {
            get {
                return ResourceManager.GetString("lbNoOneKick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string lbPassword {
            get {
                return ResourceManager.GetString("lbPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string lbPasswordSignIn {
            get {
                return ResourceManager.GetString("lbPasswordSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 10 to 50 characters, with letters and numbers.
        /// </summary>
        public static string lbPasswordValid {
            get {
                return ResourceManager.GetString("lbPasswordValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recover Password.
        /// </summary>
        public static string lbRecoverPassword {
            get {
                return ResourceManager.GetString("lbRecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Score: {0}.
        /// </summary>
        public static string lbScore {
            get {
                return ResourceManager.GetString("lbScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unknown user.
        /// </summary>
        public static string lbUnknownUser {
            get {
                return ResourceManager.GetString("lbUnknownUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Name.
        /// </summary>
        public static string lbUserName {
            get {
                return ResourceManager.GetString("lbUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 5 to 50 characters. Use letters, numbers, or _.
        /// </summary>
        public static string lbUserNameValid {
            get {
                return ResourceManager.GetString("lbUserNameValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verify your password.
        /// </summary>
        public static string lbVerifyPassword {
            get {
                return ResourceManager.GetString("lbVerifyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Waiting for player....
        /// </summary>
        public static string lbWaitingForPlayer {
            get {
                return ResourceManager.GetString("lbWaitingForPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bear.
        /// </summary>
        public static string mapOptionBear {
            get {
                return ResourceManager.GetString("mapOptionBear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cat.
        /// </summary>
        public static string mapOptionCat {
            get {
                return ResourceManager.GetString("mapOptionCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dog.
        /// </summary>
        public static string mapOptionDog {
            get {
                return ResourceManager.GetString("mapOptionDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Action failed.
        /// </summary>
        public static string titleActionFailed {
            get {
                return ResourceManager.GetString("titleActionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm Kick.
        /// </summary>
        public static string titleConfirmKick {
            get {
                return ResourceManager.GetString("titleConfirmKick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete friend.
        /// </summary>
        public static string titleDeleteFriend {
            get {
                return ResourceManager.GetString("titleDeleteFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Format not supported.
        /// </summary>
        public static string titleFileFormat {
            get {
                return ResourceManager.GetString("titleFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leave room.
        /// </summary>
        public static string titleLeaveRoom {
            get {
                return ResourceManager.GetString("titleLeaveRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No one to kick.
        /// </summary>
        public static string titleNoOneKick {
            get {
                return ResourceManager.GetString("titleNoOneKick", resourceCulture);
            }
        }
    }
}
